version: "3"

services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data: {}
